export const weeklyPooja = [
    {
        name: "Satyanarayan Pooja",
        pic: "./WeeklyPooja/1.jpg",
        use: "The puja is also performed to promote family unity and harmony.",
        price: 501,
        timing: "08:00 PM Monday",
        slug: "satyanarayan-pooja"
    },
    {
        name: "Shani Graha Shanti Pooja",
        pic: "./WeeklyPooja/2.jpg",
        use: "To improve Health, Well-being and Financial Stability",
        price: 501,
        timing: "",
        timing: "",
        slug: "shani-graha-shanti-pooja"
    },
    {
        name: "Ganesh Pooja",
        pic: "./WeeklyPooja/3.webp",
        use: "Gaining success in whether it be in academics, career, business, or personal life",
        price: 501,
        timing: "",
        slug: "ganesh-pooja"
    },
    {
        name: "Shiv Pooja",
        pic: "./WeeklyPooja/4.jpg",
        use: "Destruction of Negativity and Removal of Obstacles. Get blessings for good health and well-being",
        price: 501,
        timing: "",
        slug: "shiv-pooja"
    },
    {
        name: "Baba Lokenath Pooja",
        pic: "./WeeklyPooja/5.jpg",
        use: "Protection from Calamities, Health and Well-being",
        price: 501,
        timing: "",
        slug: "baba-lokenath-pooja"
    },
    {
        name: "Shri Laxmi Pooja",
        pic: "./WeeklyPooja/6.jpg",
        use: "Invoke Wealth & Attract Success in Career & Business, also To bring overall material well-being, including success in business, career, and personal life.",
        price: 501,
        timing: "",
        slug: "shri-laxmi-pooja"
    },
    {
        name: "Radha Krishna Pooja",
        pic: "./WeeklyPooja/7.jpg",
        use: "To remove obstacles and challenges in life, providing a clear and smooth path for personal and spiritual growth",
        price: 501,
        timing: "",
        slug: "radha-krishna-pooja"
    },
    {
        name: "Gau Mata Pooja",
        pic: "./WeeklyPooja/8.jpg",
        use: "Allow the divinity of the Goddess to enter your home and permeate every corner with the positive energy generated by the ritual.",
        price: 501,
        timing: "",
        slug: "gau-mata-pooja"
    },
    {
        name: "Maha Rudrabhishek Pooja",
        pic: "./WeeklyPooja/9.jpg",
        use: "Seek divine assistance and blessings for success in various endeavors, including career, business, and personal pursuits",
        price: 501,
        timing: "",
        slug: "maha-rudrabhishek-pooja"
    },
    {
        name: "Hanuman Pooja",
        pic: "./WeeklyPooja/10.jpg",
        use: "Gain strength, courage, and resilience to face challenges in life.",
        price: 501,
        timing: "",
        slug: "hanuman-pooja"
    },
    {
        name: "Mahalaxmi Aarti",
        pic: "./WeeklyPooja/11.jpg",
        use: "Resolution of debts, financial stability, and the removal of any hindrances in financial affairs.",
        price: 501,
        timing: "",
        slug: "mahalaxmi-aarti"
    },
    {
        name: "Maa Mangal Chandi Pooja",
        pic: "./WeeklyPooja/12.jpg",
        use: "Removal of hurdles in their personal, professional, and spiritual paths.",
        price: 501,
        timing: "",
        slug: "maa-mangal-chandi-pooja"
    },
    {
        name: "Sawaraswati Pooja",
        pic: "./WeeklyPooja/13.jpg",
        use: "Saraswati Puja can bless them with eloquence, clarity of speech, and effective communication skills",
        price: 501,
        timing: "",
        slug: "sawaraswati-pooja"
    },
    {
        name: "Navgraha Shanti Pooja",
        pic: "./WeeklyPooja/14.jpg",
        use: "To seek protection from illnesses and to promote general well-being.",
        price: 501,
        slug: "navgraha-shanti-pooja"
    },
    {
        name: "Kali Puja during Amavasya",
        pic: "./WeeklyPooja/15.jpg",
        use: "To seek her divine intervention to remove hurdles in their personal, professional, and spiritual paths",
        price: 501,
        slug: "kali-pooja-amavasya"
    },
]